# Generated by Django 4.2.6 on 2023-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
