# Generated by Django 4.2.6 on 2023-12-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_masterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
